In [3]:
import numpy as np

In [7]:
one_dimensional_array = np.array([1.2,2.4,1.0,3.1,3.2,1.2])

In [8]:
print(one_dimensional_array)

[1.2 2.4 1.  3.1 3.2 1.2]


In [11]:
two_dimensional_array = np.array([[1,2],[3,4],[5,6]])

In [12]:
print(two_dimensional_array)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
sequence_of_integers = np.arange(5,12)

In [14]:
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [15]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))

In [16]:
print(random_integers_between_50_and_100)

[55 65 62 88 52 51]


In [17]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))

In [18]:
print(random_integers_between_50_and_100)

[84 98 68 88 93 56]


In [19]:
random_floats_between_0_and_1 = np.random.random([6])

In [20]:
print(random_floats_between_0_and_1)

[0.20129794 0.88821863 0.63857038 0.21578613 0.21147911 0.19525783]


In [21]:
random_float_between_2_and_3 = random_floats_between_0_and_1 + 2

In [22]:
print(random_float_between_2_and_3)

[2.20129794 2.88821863 2.63857038 2.21578613 2.21147911 2.19525783]


In [23]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3

In [24]:
print(random_integers_between_150_and_300)

[252 294 204 264 279 168]


# TASK1

In [28]:
feature = np.random.randint(low=6, high=21, size=[15])

In [29]:
print(feature)

[ 9 16  7 10 10 18  6 15 12 18  7 14  8 13 19]


In [30]:
label = 3*feature + 4

In [31]:
print(label)

[31 52 25 34 34 58 22 49 40 58 25 46 28 43 61]


In [32]:
feature = np.arange(6,21)

In [33]:
label = 3*feature + 4

In [34]:
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [35]:
noise = np.random.random(low=-2, high=2, size = len(label))

TypeError: random() got an unexpected keyword argument 'low'

In [36]:
np.random.random.help()

AttributeError: 'builtin_function_or_method' object has no attribute 'help'

In [37]:
noise = np.random.randint(low=-2, high=2, size=len(label)) + np.random.random()

In [38]:
print(noise)

[-0.3014941  0.6985059  1.6985059  0.6985059  1.6985059  1.6985059
 -1.3014941 -1.3014941  0.6985059 -1.3014941  0.6985059 -0.3014941
 -0.3014941  1.6985059  0.6985059]


In [39]:
label = label + noise

In [40]:
print(label)

[21.6985059 25.6985059 29.6985059 31.6985059 35.6985059 38.6985059
 38.6985059 41.6985059 46.6985059 47.6985059 52.6985059 54.6985059
 57.6985059 62.6985059 64.6985059]


In [41]:
import pandas as pd

In [42]:
my_data = np.array([[0, 3],[10,7],[20,9],[30,14],[40,15]])

In [72]:
print(my_data)

[[ 0  3]
 [10  7]
 [20  9]
 [30 14]
 [40 15]]


In [43]:
my_column_names = ['temperature', 'activity']

In [44]:
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

In [45]:
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


In [46]:
my_dataframe["adjusted"]=my_dataframe["activity"] + 2

In [47]:
print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


In [48]:
print(my_dataframe.head(3))

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11


In [49]:
print(my_dataframe.head(3), '\n')

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11 



In [50]:
print(my_dataframe.iloc[[2]])

   temperature  activity  adjusted
2           20         9        11


In [51]:
print(my_dataframe[1:4])

   temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16


In [52]:
print(my_dataframe['temperature'])

0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int64


# TASK 1 DATAFRAMES

In [85]:
my_values = np.array([np.random.randint(low=0, high=101, size=4),np.random.randint(low=0, high=101, size=4),np.random.randint(low=0, high=101, size=4)])

In [86]:
print(my_values)

[[44 17 83 18]
 [ 1 95 30  0]
 [ 2 32 13 53]]


In [68]:
my_columns = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

In [76]:
taks_dataframe = pd.DataFrame(data=my_values, columns=my_columns)

In [77]:
print(taks_dataframe)º

   Eleanor  Chidi  Tahani  Jason
0       92     27      19     19
1       88     81      90     89
2       81     66      64     37


In [87]:
print(my_values.shape)

(3, 4)


In [89]:
print(taks_dataframe['Eleanor'].head(1))

0    92
Name: Eleanor, dtype: int64


In [90]:
taks_dataframe['Janet' ] = taks_dataframe['Tahani']+taks_dataframe['Jason']

In [91]:
print(taks_dataframe)

   Eleanor  Chidi  Tahani  Jason  Janet
0       92     27      19     19     38
1       88     81      90     89    179
2       81     66      64     37    101


In [92]:
reference = taks_dataframe

In [93]:
print(taks_dataframe['Jason'][1])

89


In [94]:
print(reference['Jason'][1])

89


In [95]:
taks_dataframe.at[1,'Jason']=taks_dataframe['Jason'][1] + 5

In [96]:
print(taks_dataframe)

   Eleanor  Chidi  Tahani  Jason  Janet
0       92     27      19     19     38
1       88     81      90     94    179
2       81     66      64     37    101


In [97]:
print(reference)

   Eleanor  Chidi  Tahani  Jason  Janet
0       92     27      19     19     38
1       88     81      90     94    179
2       81     66      64     37    101


In [99]:
copy = taks_dataframe.copy()

In [100]:
print(taks_dataframe['Tahani'][1])

90


In [101]:
print(copy['Tahani'][1])

90


In [104]:
taks_dataframe.at[1, 'Tahani'] = 0

In [105]:
print(taks_dataframe)

   Eleanor  Chidi  Tahani  Jason  Janet  tahani
0       92     27      19     19     38     NaN
1       88     81       0     94    179     0.0
2       81     66      64     37    101     NaN


In [106]:
print(copy)

   Eleanor  Chidi  Tahani  Jason  Janet
0       92     27      19     19     38
1       88     81      90     94    179
2       81     66      64     37    101
